# Generated by Django 3.2.9 on 2021-12-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0002_auto_20211207_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('cloths', 'cloths'), ('food', 'food'), ('shoes', 'shoes'), ('iots', 'iots'), ('books', 'books'), ('sports', 'sports')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
