# Generated by Django 3.2.9 on 2021-12-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0003_auto_20211208_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='user',
        ),
    ]
