# Generated by Django 3.2.9 on 2021-12-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_toCart',
            new_name='Addtocart',
        ),
    ]
