# Generated by Django 3.2.9 on 2022-01-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0006_rename_add_tocart_addtocart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addtocart',
            new_name='Cart',
        ),
    ]
