# Generated by Django 3.2.9 on 2022-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0007_rename_addtocart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
