# Generated by Django 3.2.9 on 2022-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
