# Generated by Django 3.2.9 on 2022-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0013_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
