# Generated by Django 3.2.9 on 2022-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBazzar', '0015_auto_20220108_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
